
run_type = "sampling"
device = "cpu"
json_out_config = "_sampling.json"

[parameters]

model_file = "TL_reinvent.model.26.chkpt"
smiles_file = "stan_smi.smi"
sample_strategy = "beamsearch"

output_file = 'new_pest_1.csv'

num_smiles = 5
unique_molecules = true
randomize_smiles = true
